admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

static:
    resource: "@StaticBundle/Controller/"
    type:     annotation
    prefix:   /

ajax:
    resource: "@AjaxBundle/Controller/"
    type:     annotation
    prefix:   /

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin